name: Action checkout version 4

on: [workflow_dispatch]

jobs:
  build:
    name: action checkout verison 4
    runs-on: ubuntu-20.04-ppc64le

    steps:
      - uses: actions/checkout@v4

      - name: demo workflow job for action checkout version 4  
        run: echo This is a demo start workflow with action checkout version 4
