name: Action checkout version 2

on: [workflow_dispatch]

jobs:
  build:
    name: action checkout version 2
    runs-on: ubuntu-latest #ubuntu-20.04-ppc64le

    steps:
      - uses: actions/checkout@v2

      - name: demo workflow job
        run: echo This is a demo start workflow
