name: Cpp test

on: [workflow_dispatch]

jobs:
  build:
    name: cpp test example  
    runs-on: ubuntu-20.04-ppc64le
           
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Cpp
        run: |
          sudo apt-get install -y  build-essential
          echo g++ version after
          g++ --version
          
      - name: execution
        run: |
          g++ -o hello hello.cpp
          hello
        
      # - name: exection of cpp
      #   run: apt install -y build-essential
      - name: printing 
        run: echo "completed"
