name: java-example-action

on: [workflow_dispatch]

jobs:
  java-example:
    runs-on: ubuntu-latest-ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: 11
      - run: |
          javac Main.java
          java Main
